# Site
repository: gent-scholar/gent-scholar.github.io 
favicon: images/favicon.icon

# Content configuration version
version: 2

# Personal info
name: Eric Decker
title: Data Ethics Working Group Member
email: gentscholar [at] duck [dot] com
website: https://linktr.ee/ericdecker

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: decker__eric
github_username:  gent-scholar
linkedin_username: 1eric0decker1

# Additional icon links
additional_links:
- title: Research Gate
  icon: fas fa-globe
  url: https://www.researchgate.net/profile/Eric_Decker2
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, my name is Eric and I am currently a Data Ethics Working Group Member specialising on Foundation Models' regulation at [The Alan Turing Institute](https://www.turing.ac.uk/research/interest-groups/data-ethics-group), GBR. Formerly, I was a Data Analyst of telemedicine for the Paracelsus Medical University of Salzburg and University of Salzburg, AUT. //
  See my current passion project here: [Truthfulness of LLMs](https://github.com/gent-scholar/astra-research-admission) //
  In June, I organised the [AI in Healthcare Workshop](https://warwick.ac.uk/research/priorities/productivity/eventsandactvities/aihealthcare/) at the University of Warwick and we are currently writing up the conference paper.
  I have lead a team of 4 people working on computer vision and deep neural networks as a former Machine Learning and AI Research Fellow and Scrum Master at [Launchpad.AI](https://www.fellowship.ai/).
  Before that I have undertaken Causality Research for [Dr. Neil LLoyd](https://warwick.ac.uk/fac/soc/economics/staff/nlloyd/) at Warwick Department of Economics. 
  Overall, my [Don Lavoie Fellowship](https://www.mercatus.org/students/don-lavoie-fellows) at the Mercatus Centre, USA in social sciences and public policy and other work, research, and volunteering experiences at a number of organisations have enabled my teamwork and leadership skills.

  I am most skilled in: <mark>Python | fast.ai, Transformers, and PyTorch</mark>, <mark>R</mark>, <mark>Stata</mark>, <mark>QGIS</mark>, <mark>Convolutional Neural Networks</mark>, <mark>Time Series Analysis</mark>, <mark>Computer Vision</mark> and <mark>Spatial Analysis</mark>. 

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Computer vision change detection
        link: https://github.com/FellowshipComputerVision/Change_Detection_Fellowship_Project
        # link_text: Project Website
        additional_links:
            - title: Change detection for land-use land-cover
              icon: fab fa-github
              url: https://github.com/gent-scholar/land-cover-change-detection
            # - title:  Github page for project (eg. sproogen/modern-resume-theme)
            #   icon: fab fa-github
            #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
            Research Fellowship in Data Science & Machine Learning working on computer vision change detection with satellite imagery data for the Hawaii Land Trust.
        description: | # this will include new lines to allow paragraphs
            I was leading a team of 4 as Scrum Master for a project of <mark>computer vision</mark> for the Hawaii Land Trust and implemented a <mark>deep convolutional neural network</mark> for satellite image recognition of <mark>land-use change detection</mark>.
            Moreover, I presented a research paper and submitted weekly research paper reports for the reading group.
            Further, I co-ordinated my project's weekly demo day presentations by collating information, creating slides, presenting and clarifying issues to senior management.
            My main learnings are: computer vision, change detection using satellite imagery data, convolutional neural networks

      - layout: top-middle
        title: Bachelor Thesis - Real-time data collection of Austrian diesel prices
        link: gent-scholar/fuel-prices
        # link_text: Project Website
        additional_links:
          - title:  gent-scholar/fuel-prices
            icon: fab fa-github
            url: https://github.com/gent-scholar/fuel-prices
          # - title:  Github page for project
          #   icon: fab fa-github
          #   url: Link to project
        quote: >
            A novel approach of mining consumer diesel prices to create more consumer transparency and oversight of price impacts.
        description: | # this will include new lines to allow paragraphs
            I started this project to contribute to a new data gathering methodology for consumer oil indexes and work towards increased consumer price transparency by collecting Austrian diesel prices real-time using <mark>Python</mark> and <mark>Google Maps API</mark> as well as the Austrian regulator's E-Control website.
            My main learnings are: API accessing and webscraping data, compiling a time-series index, spatial analysis

      - layout: top-middle
        title: Free trade, labour rights, and migration
        link: https://www.researchgate.net/profile/Eric_Decker2
        # link_text: Project Website
        additional_links:
          - title:  ResearchGate
            icon: fab fa-researchgate
            url: https://www.researchgate.net/profile/Eric_Decker2
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          A field work research exchange undertaken at ITAM, Mexico City & University of Warwick, UK combining the fields of economics, sociology, and law to analyse the interaction of NAALC, the NAFTA labour side agreement.
        description: | # this will include new lines to allow paragraphs
          The project contributed to the interdisciplinary research of human rights and macroeconomics by undertaking an extensive <mark>Qualitative Research</mark>.
          I focussed on NAALC, NAFTA's labour side agreement by uniting the disciplines of sociology for migration, macreconomics for free trade, and law for labour rights.
          The results were presented at: <mark>International Conference for Undergraduate Research, Coventry, UK</mark>, <mark>British Conference for Undergraduate Research, Leeds, UK</mark>, and at the <mark>Undergraduate Research Support Scheme, Coventry, UK</mark>.
          I am grateful for the research funding granted by the <mark>Undergraduate Research Support Scheme</mark> by the University of Warwick to undertake the research exchange to ITAM, Mexico City.
          Many thanks go to my supervisors for their guidance and expertise: Assoc. Prof. Dr. Stefania Paredes Fuentes, University of Warwick and Dr. Christina Wagner Faegri, ITAM.
          My main learnings are: free trade and labour law within NAFTA, Central/North American migration

      - layout: top-middle
        title: NLP DistilBERT IMDb dataset - Launchpad.AI admission test
        link: https://github.com/gent-scholar/NLP-IMDB
        # link_text: Project Website
        additional_links:
          - title:  gent-scholar/ NLP-IMDB
            icon: fab fa-github
            url: https://github.com/gent-scholar/fuel-prices
          # - title:  Github page for project
          #   icon: fab fa-github
          #   url: Link to project
        quote: >
          Launchpad.AI's admission test of sentiment analysis by using a pre-trained DistilBERT model to inference on IMDB dataset. 
        description: | # this will include new lines to allow paragraphs
          Tackling the sentiment analysis challenge, I used a pre-trained <mark>DistilBERT</mark>, a more efficient, smaller but almost as accurate version of BERT by Hugging Face designed for word completion and applied it to sentiment analysis. 
          My main learnings are: NLP, sentiment analysis, Hugging Face plattform, pre-trained DistilBERT model
          
          
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
    
      - layout: left
        title: The Alan Turing Institute
        link: https://www.turing.ac.uk/research/interest-groups/data-ethics-group
        link_text: Data Ethics Group
        sub_title: Data Ethics Working Group Member
        caption: Jun 2023 - Present
        quote: >
          Advancing telemedicine for a better medical system in German speaking (DACH) countries by analysing needs and wants from medical experts and laypeople. 
        description: | # this will include new lines to allow paragraphs
            I am jointly establishing The Alan Turing Institute’s position on Foundation Models' regulation in a team of 30 AI and industry experts, forthcoming as a co-author in the Harvard Data Science Review.
     
      - layout: left
        title: University of Salzburg and Paracelsus Medical University of Salzburg
        link: 
        link_text: Work in Progress
        sub_title: Quantitative Data Analyst
        caption: Jun 2021 - Oct 2023
        quote: >
          Advancing telemedicine for a better medical system in German speaking (DACH) countries by analysing needs and wants from medical experts and laypeople. 
        description: | # this will include new lines to allow paragraphs
            I am involved in a 4 part process. I undertook experts interview surveys for over 40 medical experts in the DACH countries.
            Designed balanced and weighted online surveys of 5,500 people in DACH countries.
            Collated, cleaned, and analysed data about attituded to telemedicine in <mark>R</mark>.
            Drafted final report of mixed methods study in English and German in a team of 4.
            My main learnings are: <mark>(qualitative) data gathering</mark> of large-scale medical and technology surveys and expert interviews and their <mark>data analysis in R</mark>.
            
      - layout: left
        title: Launchpad.AI
        link: https://www.fellowship.ai/
        link_text: fellowship.ai
        sub_title: Scrum Master and Research Fellow
        caption: January 2023 - April 2023
        quote: >
          Protecting biodiversity via land-use change detection for the Hawaii Land Trust using deep learning convolutional neural networks managing a team of 4.
        description: | # this will include new lines to allow paragraphs
            The Hawaii Land Trust (HILT) wants to monitor its land for land-use land-cover changes through satellite imagery.
            I lead a team of 4 people training a <mark>Siamese CNN</mark> and fine-tuning it with daily satellite imagery data from Hawaii to apply it to HILT's local environment.
            My main learnings are: implementing in a team <mark>computer vision change detection</mark> with <mark>deep neural networks</mark>.

      - layout: left
        title: Don Lavoie Fellow
        link: https://www.mercatus.org/students/don-lavoie-fellows
        link_text: Don Lavoie Fellowship
        sub_title: Research Fellow
        caption: Sep 2021 - June 2023
        quote: >
          Fellows join a network of Mercatus students, alumni, faculty, and scholars who are conducting and engaging with cutting edge research in contemporary political economy.
        description: | # this will include new lines to allow paragraphs
            Don Lavoie Fellowship is a competitive, renewable, and online fellowship program for advanced undergraduates, recent graduates, and early-stage graduate students.
            Fellowships are open to students from any discipline who are interested in studying key ideas in political economy and learning how to utilize these ideas in academic and policy research.
            Throughout the fellowship I developed policy solutions with field-experts and international fellows to current social, political, and economic issues.
            My main learnings are: developing policy-making solutions to political, economic, and social challenges.

      - layout: left
        title: University of Warwick, Department of Economics
        link: https://github.com/Najuh/3_code
        link_text: Unemployment/Self-Employment South Africa
        sub_title: Research Assistant
        caption: Jul 2022 - Dec 2022
        quote: >
          Evolving understanding of high unemployment and low self-employment puzzle in South Africa through an historical lens on spatial mining data under Apartheid South Africa.
        description: | # this will include new lines to allow paragraphs
            I was involved in 3 stage process in working with historical mining data.
            First, Identified microeconometric instrumental variable strategies for explaining contemporary high unemployment and low self-emplyoment puzzle.
            Then, I visualised innovatively spatial data and maps using <mark>QGIS</mark> and <mark>R</mark>.
            Finally, I applied econometric spatial inference South African historical spatial mining data utilising <mark>GitHub</mark> for version control and R for first-stage regressions in 2 least squares regressions.
            My main learnings are: spatial data analysis in R, visualisation of spatial data using R and QGIS, version control using Github, instrumental variable identification strategy.
   
  - title: Conference Presentations # Title for the section
    layout: list # Type of content section (list/text)
    content:
    
    - layout: top-middle
      title: Organisation of AI in Healthcare Workshop
      link: https://warwick.ac.uk/research/priorities/productivity/eventsandactvities/aihealthcare/
      link_text: AI in Healthcare
      sub_title: Coventry, GB
      caption: 29-June-2023
      description: |
            Title: AI in Healthcare: A closer look at Interdisciplinarity for Improved Innovation in Future Clinical and Work Practices. 
    
    - layout: top-middle
      title: 20th STOREP Annual Conference  
      link: https://www.storep.org/wp/en/20th-storep-annual-conference-15-17-june-2023/
      link_text: STOREP 2023
      sub_title: Bari, IT
      caption: 15-17-Jun-2023
      description: |
            Title: How are we moving? - a new data gathering approach for consumer oil
      
    - layout: top-middle
      title: British Conference for Undergraduate Research (BCUR)
      link: https://warwick.ac.uk/fac/soc/economics/news/2021/5/warwick_economics_students_present_their_research_at_bcur_2021/
      link_text: BCUR 2021
      sub_title: Leeds, GB
      caption: 13-Apr-2021
      description: |
            Title: Free trade, labour rights, and migration
        
    - layout: top-middle
      title: 10 Year Anniversary of Economy for the Common Good (ECG)
      link: https://web.ecogood.org/media/filer_public/98/7b/987bdb6d-0b17-4636-90c4-f8a25ca71c5b/2020_10_12_pi-10-jahre-gwoe-salzburg-nachbericht.pdf
      link_text: 10 year anniversary conference
      sub_title: Salzburg, AT
      caption: 10-Oct-2020
      description: |
            Title: Work for pluralism in economics with Rethinking Economics International
        
    - layout: top-middle
      title: International Conference for Undergraduate Research (ICUR)
      link: https://www.icurportal.com/gallery/icur-2019-image-gallery/
      link_text: ICUR 2019
      sub_title: Coventry, GB
      caption: 24-Sep-2019
      description: |
            Title: Macroeconomics and human rights
        
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Warwick University and year abroad at University of Salzburg
        caption: 2018 - 2022
        sub_title: BSc (Hons) Economics
        quote: >
          In 1964, founder J.R. “Dick” Sargent created a Department with the first few professors and graduate students. He envisioned a department that would use, and train its students to use, the critical mathematical tools needed for analysis of complex economic issues – a legacy that continues to the present day.
        description: | # this will include new lines to allow paragraphs
          During my time at Warwick and a year abroad at the University of Salzburg I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines.
          My courses most relevant to my work included amongst others neural networks, machine learning, advanced macroeconometrics, quality of social science data, time-series econometrics, microeconometrics, mathematical statistics, and game theory.
          I spent my free time establishing and leading the student society *Rethink Economics Warwick* of *Rethinking Economics International* on roles such as *External Relations Officer* and *Co-ordinator* organising many academic talks and panel discussions.

  - title: Grants & Affiliations
    layout: list
    content:
    
      - layout: top-middle
        title: Grant recipient
        sub_title: Undergraduate Research Support Scheme (URSS)
        link: https://warwick.ac.uk/services/skills/urss/
        link_text: URSS
        
      - layout: top-middle
        title: Don Lavoie Fellow
        sub_title: Mercatus Centre
        link: https://www.mercatus.org/students/don-lavoie-fellows
        link_text: Mercatus Centre
       
      - layout: top-middle 
        title: Young Affiliate
        sub_title: Constitutional Economics and Social Philosophy (NOUS)
        link: https://nous.network/young-affiliates/
        link_text: NOUS
        
      - layout: top-middle 
        title: Partnership and Strategy Officer
        sub_title: Rethinking Economics International (RE Int)
        link: https://www.rethinkeconomics.org/about/who-we-are/
        link_text: RE Int
        
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in AI and machine learning some of my other interests and hobbies are:
      - Volunteering at an Ukrainian Orphanage
      - Writing Poetry in German, English, Spanish, and French
      - Photography
      - Sailing
      - Sewing
      
     # ICUR 2019 at the University of Warwick
     # ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")
     # ![ICUR](images/ICUR.jpg)

# Footer
footer_show_references: true
references_title: Copyright Eric Decker 2023

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
