# Site
repository: gent-scholar/gent-scholar.github.io 
favicon: images/favicon.icon

# Content configuration version
version: 2

# Personal info
name: Eric Decker
title: Research Fellow and Research Assistant
email: gentscholar@duck.com
website: https://linktr.ee/ericdecker

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: decker__eric
github_username:  gent-scholar
linkedin_username: 1eric0decker1

# Additional icon links
additional_links:
- title: ericdecker
  icon: fas fa-globe
  url: https://linktr.ee/ericdecker
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, my name is Eric and I am a Research Fellow at Launchpad.AI and Research Assistant at the University of Salzburg. As well as researching in social and health sciences myself and in a team I also have experience in computer vision and neural networks. Currently, I am also a Don Lavoie Fellow for Political Economy at the Mercatus Centre, George Mason University and have worked and volunteered at a number of organisations gaining teamwork and leadership skills.

  I am most skilled in: <mark>Python</mark>, <mark>R</mark>, <mark>Stata</mark>, <mark>Convolutional Neural Networks</mark> and <mark>Computer vision</mark>. 

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Computer vision change detection
        link: gent-scholar/FellowshipAI_Change_Detection_Project
        # link_text: Project Website
        additional_links:
            - title: Change detection for land use land cover
              icon: fab fa-github
              url: https://github.com/gent-scholar/land-cover-change-detection
            # - title:  Github page for project (eg. sproogen/modern-resume-theme)
            #   icon: fab fa-github
            #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
            Research Fellowship in Data Science & Machine Learning working on computer vision change detection with satellite imagery data for the Hawaii Land Trust.
        description: | # this will include new lines to allow paragraphs
            I am leading a team of 4 for a project of <mark>computer vision</mark> for the Hawaii Land Trust and implemented a <mark>deep convolutional neural network</mark> for satellite image recognition of <mark>land-use change detection</mark>.
            Moreover, I presented a research paper and submitted weekly research paper reports for the reading group.
            Further, I co-ordinated my project's weekly demo day presentations by collating information, creating slides, presenting and clarifying issues to senior management.
            My main learnings are: computer vision, change detection using satellite imagery data, convolutional neural networks

      - layout: top-middle
        title: Bachelor Thesis - Real-time data collection of Austrian diesel prices
        link: gent-scholar/fuel-prices
        # link_text: Project Website
        additional_links:
          - title:  gent-scholar/fuel-prices
            icon: fab fa-github
            url: https://github.com/gent-scholar/fuel-prices
          # - title:  Github page for project
          #   icon: fab fa-github
          #   url: Link to project
        quote: >
            A novel approach of mining consumer diesel prices to create more consumer transparency and oversight of price impacts.
        description: | # this will include new lines to allow paragraphs
            I started this project to contribute to a new data gathering methodology for consumer oil indexes and work towards increased consumer price transparency by collecting Austrian diesel prices real-time using <mark>Python</mark> and <mark>Google Maps API</mark> as well as the Austrian regulator's E-Control website.
            My main learnings are: API accessing and webscraping data, compiling a time-series index, spatial analysis

      - layout: top-middle
        title: Free trade, labour rights, and migration
        link: https://www.researchgate.net/profile/Eric_Decker2
        # link_text: Project Website
        additional_links:
          - title:  ResearchGate
            icon: fab fa-researchgate
            url: https://www.researchgate.net/profile/Eric_Decker2
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          A field work research exchange undertaken at ITAM, Mexico City & University of Warwick, UK combining the fields of economics, sociology, and law to analyse the interaction of NAALC, the NAFTA labour side agreement.
        description: | # this will include new lines to allow paragraphs
          The project contributed to the interdisciplinary research of human rights and macroeconomics by undertaking an extensive <mark>Qualitative Research</mark>.
          I focussed on NAALC, NAFTA's labour side agreement by uniting the disciplines of sociology for migration, macreconomics for free trade, and law for labour rights.
          The results were presented at: <mark>International Conference for Undergraduate Research, Coventry, UK</mark>, <mark>British Conference for Undergraduate Research, Leeds, UK</mark>, and at the <mark>Undergraduate Research Support Scheme, Coventry, UK</mark>.
          I am grateful for the research funding granted by the <mark>Undergraduate Research Support Scheme</mark> by the University of Warwick to undertake the research exchange to ITAM, Mexico City.
          Many thanks go to my supervisors for their guidance and expertise: Assoc. Prof. Dr. Stefania Paredes Fuentes, University of Warwick and Dr. Christina Wagner Faegri, ITAM.
          My main learnings are: free trade and labour law within NAFTA, Central/North American migration

      - layout: top-middle
        title: Launchpad.AI admission test - NLP DistilBERT ImDB dataset
        link: https://github.com/gent-scholar/NLP-IMDB
        # link_text: Project Website
        additional_links:
          - title:  gent-scholar/ NLP-IMDB
            icon: fab fa-github
            url: https://github.com/gent-scholar/fuel-prices
          # - title:  Github page for project
          #   icon: fab fa-github
          #   url: Link to project
        quote: >
          Launchpad.AI's admission test of sentiment analysis by using a pre-trained DistilBERT model to inference on IMDB dataset. 
        description: | # this will include new lines to allow paragraphs
          I started this project to contribute to a new data gathering methodology for consumer oil indexes and work towards increased consumer price transparency by collecting Austrian diesel prices real-time using <mark>Python</mark> and <mark>Google Maps API</mark> as well as the Austrian regulator's E-Control website.
          My main learnings are: NLP, sentiment analysis, Hugging Face, pre-trained DistilBERT model
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Launchpad.AI
        link: https://www.fellowship.ai/
        link_text: fellowship.ai
        sub_title: Research Fellow
        caption: January 2023 - Present
        quote: >
          Protecting biodiversity via land-use change detection for the Hawaii Land Trust using deep learning convolutional neural networks managing a team of 4.
        description: | # this will include new lines to allow paragraphs
            The Hawaii Land Trust (HILT) wants to monitor its land for land-use land-cover changes through satellite imagery.
            I lead a team of 4 people training a <mark>Siamese CNN</mark> and fine-tuning it with daily satellite imagery data from Hawaii to apply it to HILT's local environment.
            
      - layout: left
        title: Don Lavoie Fellow
        link: https://www.mercatus.org/students/don-lavoie-fellows
        link_text: Don Lavoie Fellowship
        sub_title: Research Fellow
        caption: Sep 2021 - Present
        quote: >
          Fellows join a network of Mercatus students, alumni, faculty, and scholars who are conducting and engaging with cutting edge research in contemporary political economy.        description: | # this will include new lines to allow paragraphs
        description: |
            Don Lavoie Fellowship is a competitive, renewable, and online fellowship program for advanced undergraduates, recent graduates, and early-stage graduate students.
            Fellowships are open to students from any discipline who are interested in studying key ideas in political economy and learning how to utilize these ideas in academic and policy research.
            Throughout the fellowship I developed policy solutions with field-experts and international fellows to current social, political, and economic issues.
            My main learnings are: research of policy-making solutions to political, economic, and social challenges
            
     
     - layout: left
        title: University of Salzburg and Paracelsus Medical University of Salzburg
        link:
        link_text: Work in Progress
        sub_title: Quantitative Research Assistant
        caption: Jun 2021 - Present
        quote: >
          Advancing telemedicine for a better medical system in German speaking (DACH) countries by analysing needs and wants from medical experts and laypeople. 
        description: | # this will include new lines to allow paragraphs
            I am involved in a 4 part process. I undertook experts interview surveys for over 40 medical eperts in DACH countries.
            Designed balanced and weighted online surveys for 1,500 non-expert surveys in DACH countries.
            Collated, cleaned, and analysed data about attituded to telemedicine in <mark>R</mark>.
            Drafted final report of mixed methods study in English and German leading a team of two.
            My main learnings are: methodology for survey design for data gathering, data analysis in R.
            
      - layout: left
        title: University of Warwick, Department of Economics
        link: https://github.com/Najuh/3_code
        link_text: Unemployment/Self-Employment South Africa - Work in Progress
        sub_title: Research Assistant
        caption: July 2022 - Dec 2022
        quote: >
          Evolving understanding of high unemployment and low self-employment puzzle in South Africa through an historical lens on spatial mining data under Apartheid South Africa.
        description: | # this will include new lines to allow paragraphs
            I was involved in 3 stage process in working with historical mining data.
            First, Identified microeconometric instrumental variable strategies for explaining contemporary high unemployment and low self-emplyoment puzzle.
            Then, I visualised innovatively spatial data and maps using <mark>QGIS</mark> and <mark>R</mark>.
            Finally, I applied econometric spatial inference South African historical spatial mining data utilising <mark>GitHub</mark> for version control and R for first-stage regressions in 2 least squares regressions.
            My main learnings are: spatial data analysis in R, visualisation of spatial data using R and QGIS, version control using Github, instrumental variable identification strategy
   
  - title: Conference Presentations # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: middle
        title: British Conference for Undergraduate Research (BCUR), Leeds, GB
        caption: 13-April-2021
        sub_title: Focus: Free trade, labour rights, and migration
        
      - layout: middle
        title: 10 Year Anniversary of Economy for the Common Good, Salzburg, AT
        caption: 10-October-2020
        sub_title: Focus: Work for pluralism in economics with Rethinking Economics International
        
      - layout: middle
        title: International Conference for Undergraduate Research (ICUR), Coventry, GB
        caption: 24-September-2019
        sub_title: Focus: Group presentation; Macroeconomics and human rights
        
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Warwick University and year abroad at University of Salzburg
        caption: 2018 - 2022
        sub_title: BSc (Hons) Economics
        quote: >
          In 1964, founder J.R. “Dick” Sargent created a Department with the first few professors and graduate students. He envisioned a department that would use, and train its students to use, the critical mathematical tools needed for analysis of complex economic issues – a legacy that continues to the present day.
        description: | # this will include new lines to allow paragraphs
          During my time at Warwick and a year abroad at the University of Salzburg I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines.
          My courses most relevant to my work included amongst others neural networks, machine learning, advanced macroeconometrics, quality of social science data, time-series econometrics, microeconometrics, mathematical statistics, and game theory.
          I spent my free time establishing and leading the student society *Rethink Economics Warwick* of *Rethinking Economics International* on roles such as *External Relations Officer* and *Co-ordinator* organising many academic talks and panel discussions.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in AI and machine learning some of my other interests and hobbies are:
      - Volunteering at an Orphanage
      - Writing Poetry in German, English, Spanish, and French
      - Photography
      - Sailing
      - Sewing
      
     # Look at this cool image  
     # ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
references_title: References on request

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
